### ISSUE TITLE
Starbuck.exe fails to launch application "application configured incorrectly" error (2040806)

### ISSUE THREAD

**Issue by dbrgss** [blackberry/Ripple-Framework#11]
When trying to run the Windows version of starbuck some machines are failing to launch with an "application configured incorrectly error.

**Comment by dbrgss** [comment]
Starbuck.exe fails to launch application "application configured incorrectly" error.

Note that there is no config.ini file when the .exe installer is used.

Here is event log on win7,       it looks like missing some runtime files. 
"Activation context generation failed for "C:\Program Files (x86)\Research In Motion\Ripple 0.9.0.0\Starbuck.exe". Dependent Assembly Microsoft.VC90.DebugCRT,processorArchitecture="x86",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8" could not be found. Please use sxstrace.exe for detailed diagnosis."

**Comment by ericpearson** [comment]
Looks like some DLL's were not included or missing from the installation. What system does this happen on so I can take a look.
