### ISSUE TITLE
Loading Wrong URL Resources (1994859)

### ISSUE THREAD

**Issue by dbrgss** [blackberry/Ripple-Framework#14]
load wrong page source from omnibar url ,

case 1 
1)  UI page points to http://CI0000007.rim.net/next/index.html

2) load another page from same host , "http://CI0000007.rim.net/yui/index.html"

3) web inspector indicates that, all the resources are still try loading from http://CI0000007.rim.net/next/ , but not http://CI0000007.rim.net/yui

case 2 
 1) UI page points to http://CI0000007.rim.net/next/index.html 
 2)  load another page from different host,   such as  "http://CI00009.rim.net/yui/index.html"

   web inspector  get following error:  

SyntaxError: Parse error  XHR finished loading: "http://api.tinyhippos.com/xhr_proxy?tinyhippos_apikey=ABC&tinyhippos_rurl=http%3A//atg05-yyz.rim.net/yui/blackberry/bb_utils_yui.js". 

work around

Need put all test pages into same folder as UI .

when  make a  XHR  call ,  it always looking  under  UI path

**Comment by ghost** [comment]
This is casued by the same reason as issue 24.
Framework always receives the UI page as base document  when resolving the target file of a xhr call, no matter where the target file is located.

I verified the Chun's test case with a simple page containing an iframe to replace the UI page. The XHR call tiggered from the page of the iframe pass the correrct document ( page shown in the iframe) to resolve the target file.

**Comment by kwallis** [comment]
fixed
