### ISSUE TITLE
QT webkit while in WebInspector is causing starbuck to crash (2017422)

### ISSUE THREAD

**Issue by dbrgss** [blackberry/Ripple-Framework#15]
Steps:

1) Open up webinspector for any application loaded in starbuck
2) On the storage tab, then selected tinyHippos database, then double clicked on "persistence".

Expected:
Display the values

Actual:
Starbuck crashes. You can click to ignore the message (attached pic) and try to continue to run the application. Haven't tried further to see how stable the app is though

**Comment by kwallis** [comment]
fixed
