### ISSUE TITLE
Ripple (as a standalone tool) can be installed and run on Mac OS X Snow Leopard and Lion

### ISSUE THREAD

**Issue by jasenk** [blackberry/Ripple-Framework#18]
Acceptance Criteria:
Ripple can be installed and run on Mac OS X Snow Leopard and Lion
All tests written for the Windows version of the software need to continue to work on the Mac
Ripple will not be able to deploy a WebWorks app onto a smartphone simulator (since they are Windows only)

**Comment by kwallis** [comment]
implemented
