### ISSUE TITLE
CSS Transforms/Animations perform poorly

### ISSUE THREAD

**Issue by ndaversa** [blackberry/Ripple-Framework#21]
- http://beta.theexpressiveweb.com/#!/css3-animations
- http://beta.theexpressiveweb.com/#!/css3-transforms

Performance measured relative to Chrome 15.0.874.5 dev.

QT spikes CPU/Fan and freezes often.

**Comment by ericpearson** [comment]
Nothing we can do about this, QtWebKit lacks hardware acceleration on OS X.
