### ISSUE TITLE
To shutdown Build & Deploy service use this command, and change the start command accordingly

### ISSUE THREAD

**Issue by kwhatmough** [blackberry/Ripple-Framework#22]
Rather than killing the Build & Deploy process, please use the following for starting and stopping the B&D service:
### Start the Service

To start the Ripple Build and Deploy service on port 45660 (for example), use the following command:

```
rbd_service -start 45660
```
### Stop the Service

To stop the Ripple Build and Deploy service, use the following command (in this example, assuming the port number from above):

```
rbd_service -shutdown 45660
```

**Comment by kwhatmough** [comment]
The Build & Deploy change has been coded-up and is ready for integration. Let me know when you put this change in, and I will coordinate the integration on our side.
K.W.

**Comment by ericpearson** [comment]
The Rippe UI is still going to shut it down with the request though? Or is this in case we need to shut it down whatever reason?

**Comment by kwhatmough** [comment]
The never was any intent for the UI to shutdown RBD. The intent always was that the Framework would shutdown RBD. Initially we agreed that this would be through the XHR call. But then it was agreed that a command-line shutdown would make it easier for Framework to shutdown RBD so we added this support on our side.

**Comment by kwhatmough** [comment]
Why was this issue closed?

**Comment by ericpearson** [comment]
Oops, didn't mean to close it. But as far as I know the build service was going to be shut down by a call from the UI code when it detects the window closing by calling the shutdown URL. Has something changed?

**Comment by kwhatmough** [comment]
Actually last week Dave asked us to provide the shutdown command above. The intent is that Framework will call it on exit rather than just killing the B&D process. This will give us a chance to shutdown anything that we started (Fledge simulator, MDS simulator, etc.)

**Comment by ericpearson** [comment]
The shutdown command requires the port?

**Comment by kwhatmough** [comment]
Yes

**Comment by ericpearson** [comment]
This is now implemented, closing this issue.
