### ISSUE TITLE
QT webkit does not support gif picture (2014299)

### ISSUE THREAD

**Issue by dbrgss** [blackberry/Ripple-Framework#34]
current QT webkit does not include  image plugin , so gif pic can not render properly .
http://doc.qt.nokia.com/4.7/deployment-plugins.html

**Comment by tneil** [comment]
What does this mean.. can you not use a .gif in your web content?

**Comment by tneil** [comment]
Does this mean that we just need to pickup this plugin?

**Comment by dbrgss** [comment]
Yes this appears to be so.   Just doing a quick investigation I was able to find several articles on using status image plug-ins to support jpeg, gif, etc...   http://lists.trolltech.com/qt-interest/2008-10/msg00916.html

**Comment by ericpearson** [comment]
We need to compile with libgif.

**Comment by ericpearson** [comment]
I think this should be fixed now, at least with QtWebKit 2.2

**Comment by kwallis** [comment]
Fixed with move to QT 4.8.
