### ISSUE TITLE
Window Size and Position

### ISSUE THREAD

**Issue by tneil** [blackberry/Ripple-Framework#37]
It looks like the config.ini remembers windows size and position but it doesn't remember state.  If I have my window maximized, close it and re-open it... it makes the screen the same size as it was when it was maximized.. but it doesn't actually maximize it

[2052949]

**Comment by ericpearson** [comment]
Good point, you are correct. I'll look about fixing this for Windows. Window states vary a lot based on the OS so I will try to keep it as consistent as possible to "maximizing" across Mac and Windows.

**Comment by tneil** [comment]
Sounds good

-----Original Message-----

**Comment by kwallis** [comment]
Fixed
