### ISSUE TITLE
Application Cache Limits

### ISSUE THREAD

**Issue by ndaversa** [blackberry/Ripple-Framework#38]
In Ripple-UI we are now taking advantage of the built in browser application cache to store all of Ripple inside Starbuck for offline access.

Currently the total resources is somewhere around 4.5MB, for release this should be fine.

However there is a 5MB limit in place in most browsers for app cache. I want to make sure that we can disable that in QT so we don't run into a problem in future with resources not fully caching.

**Comment by ericpearson** [comment]
We can fix this, what size would you want it? I put in 512 MB, do you think this will be enough? It won't use that much space unless you have stored something in it, this is the only the maximum size.

**Comment by ndaversa** [comment]
512MB should be more then ample for the conceivable future.
