### ISSUE TITLE
CSS border-radius are incorrectly rendered (and truncated)

### ISSUE THREAD

**Issue by brentlintner** [blackberry/Ripple-Framework#39]
border-radius styling is not properly rendered (truncated/choppy). This affects Ripple's UI drastically and any mobile app a user is making.

Steps to reproduce:
1. Open up QTWebKit (see this [screenshot](http://dl.dropbox.com/u/8785000/border-radius.png)).

System
MacOS 10.7.1

[2052765]

**Comment by ericpearson** [comment]
It looks like it is rendering correctly when you mouse over the items?

**Comment by ericpearson** [comment]
Hey is it possible to get a snippet of the CSS or a simple web page that shows the bug? I'm working on this bug now as it's related to something else but I can't test the entire Ripple UI while doing it.

**Comment by brentlintner** [comment]
Confirmed as well it is fine when you hover over it (if it still helps).

A snippet of the CSS being used (essentially):

```
-webkit-border-radius: 5px;
-moz-border-radius: 5px;
border-radius: 5px;
```

**Comment by ericpearson** [comment]
Good news! It's fixed!

**Comment by brentlintner** [comment]
epic. thanks!

**Comment by kwallis** [comment]
Fixed
