### ISSUE TITLE
Scaled PNGs are pixellated and poorly rendered

### ISSUE THREAD

**Issue by brentlintner** [blackberry/Ripple-Framework#40]
The Ripple Logo is pixellated. Not sure if it's just scaled PNGs or another issue.

Steps to reproduce:
1. Open up QTWebKit (see this [screenshot](http://dl.dropbox.com/u/8785000/pixelation.png)).

System
MacOS 10.7.1

[2052769]

**Comment by ericpearson** [comment]
This should be fixed with the new graphics backend. I've noticed that images are much smoother.

**Comment by kwallis** [comment]
Fixed
