### ISSUE TITLE
[Win7] Ripple 0.9.0.1 does not start up on Win7 64-bit

### ISSUE THREAD

**Issue by dbrgss** [blackberry/Ripple-Framework#43]
No config.ini file is ever created. So I can't even alter it to have to directed to the correct location for the GUI

On WinXP, Win7 32-bit and Mac, Ripple can be started up just fine.

[2055376]

**Comment by ericpearson** [comment]
Works for me on Win 7 64-bit Ultimate.

**Comment by dbrgss** [comment]
Not reproducible.
