### ISSUE TITLE
[Win7] No log file is created at all. There is absolutely no way for the user to ever find out what is going on if there is a problem during the build or launch or anything else.

### ISSUE THREAD

**Issue by dbrgss** [blackberry/Ripple-Framework#44]
On winXP and Mac, the log file is created and at least the user has an idea what is going on. On Win7, nothing is logged. (Nothing is logged to the ripple command window or any external log file).

[2055363]

**Comment by ericpearson** [comment]
The log file is now placed in the temp directory for all platforms.

**Comment by dbrgss** [comment]
From: Jenny Gee 
Sent: Wednesday, October 05, 2011 9:52 AM 
To: Andrew Knox 
Cc: Jenny Gee 
Subject: Verified: BlackBerry Platform Dev Task 2055363: [Win7] No log file is created at all. There is absolutely no way for the user to ever find out what is going on if there is a problem during the build or launch or anything else. (#44) 

URL: http://mksintegrity:7001/im/issues?selection=2055363 

Verified on win7 32bit and win7 64bit for Ripple 0.9.0.3 

Verification passed
