### ISSUE TITLE
Navigating to github.com in Starbuck doesn't work

### ISSUE THREAD

**Issue by ndaversa** [blackberry/Ripple-Framework#45]
1. Open starbuck
2. Navigate to http://github.com

Expected:
Github to load in the iframe

Actual:
Nothing, error console states:
Refused to display document because display forbidden by X-Frame-Options.

**Comment by ericpearson** [comment]
This is the reason why, github uses this header. Do we want to change this behavior?

https://developer.mozilla.org/en/The_X-FRAME-OPTIONS_response_header

**Comment by ndaversa** [comment]
Well I think sites like github should work and since we disable web security anyways I don't see the value in enforcing this policy.

Also while you're looking at code like this, try open up the site yahho.ca in the omnibar, and see how it takes over all of starbuck.

Sites that attempt to takeover big window should be taken out back and shot.

**Comment by ericpearson** [comment]
We should get someone to weigh in on this. For the first problem with the X-Frame-Options I don't see an issue turning off the security on this. For the problem with sites taking over the big frame, this should fix itself when we go back to the dual browser architecture.

**Comment by kwhatmough** [comment]
www.google.com now too.
[2327551]
