### ISSUE TITLE
QTwebkit does not support any audio type (2088769)

### ISSUE THREAD

**Issue by dbrgss** [blackberry/Ripple-Framework#53]
0.9.0.3(qt4.7.3)  does not support any audio type   which cause blackberry.audio emulation failure 

PCM audio supportNo ✘MP3 supportNo ✘AAC supportNo ✘Ogg Vorbis supportNo ✘WebM supportNo ✘

**Comment by ericpearson** [comment]
This is fixed with Qt 4.8

**Comment by kwallis** [comment]
Fixed
