### ISSUE TITLE
Starbuck crashes when scrolling with main content window

### ISSUE THREAD

**Issue by ndaversa** [blackberry/Ripple-Framework#56]
Steps to reproduce:
1. Navigate to:

```
http://dl.dropbox.com/u/2623992/menu.html
```
1. Open the config panel (or enough panels so that the main content window requires scrolling)
2. scroll the main window until you reach the bottom

Actual Result:
Starbuck crashes

Expected Result:
No crash, just scrolling bliss, maybe some nice rubber banding at the bottom for good measure 

[2092554]

**Comment by ericpearson** [comment]
I have found the issue, fixing it now.

**Comment by ericpearson** [comment]
Should be fixed now

**Comment by ndaversa** [comment]
Got a link to the commit that fixes it?

**Comment by ericpearson** [comment]
Testing it now. I'll let you know when i'm finished.

**Comment by ericpearson** [comment]
I have pushed the fix it is commit fae36473e0feaa28e2baafa4b5bd550ef841adbb

**Comment by ericpearson** [comment]
This is good to go now. Please let me know if you have any issues related to scrolling.

**Comment by ndaversa** [comment]
Where can I get a build to test?
(cc @dansilivestru @gtanner)

**Comment by kwallis** [comment]
Fixed
