### ISSUE TITLE
Ripple crashes during launch on windows

### ISSUE THREAD

**Issue by dbrgss** [blackberry/Ripple-Framework#59]
when try to launch ripple on windows, it crashed immediately  .  

here is log that ripple generated : 

Thu Oct 6 14:16:56 2011:Warning:Object::connect: No such signal QtGraphicsStageWebView::loadStarted()
Thu Oct 6 14:16:56 2011:Warning:Object::connect:  (receiver name: 'progressBar')
Thu Oct 6 14:16:56 2011:Warning:Object::connect: No such signal QtGraphicsStageWebView::loadStarted()
Thu Oct 6 14:16:56 2011:Warning:Object::connect:  (receiver name: 'progressBar')
Thu Oct 6 14:16:56 2011:Warning:Object::connect: No such signal QtGraphicsStageWebView::loadProgress(int)
Thu Oct 6 14:16:56 2011:Warning:Object::connect:  (receiver name: 'progressBar')
Thu Oct 6 14:16:56 2011:Warning:Object::connect: No such signal QtGraphicsStageWebView::loadFinished(bool)
Thu Oct 6 14:16:56 2011:Warning:Object::connect:  (receiver name: 'progressBar')

(2092966)

**Comment by kwallis** [comment]
Fixed
