### ISSUE TITLE
[MacOS] Native UI corruption in HTML range input controls

### ISSUE THREAD

**Issue by brentlintner** [blackberry/Ripple-Framework#9]
_Step to Reproduce_
1. build this Ripple-UI branch: https://github.com/blackberry-webworks/Ripple-UI/tree/omnibar
2. load it in next on Ripple-Framework
3. switch to PhoneGap, and open the Geolocation panel (see range controls used for heading etc)

_System Info_

MacOS: 10.6.7

2053059

**Comment by ericpearson** [comment]
Fixed
